/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package irrigacao;

import bean.Programacao;
import dao.ProgramacaoDAO;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilTextField;

/**
 *
 * @author Marcos Vinicius
 */
public final class cadProgramacao extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    Programacao progInsUp;

    /**
     * Creates new form cadProgramacao
     */
    public cadProgramacao() {
        initComponents();
        setLocationRelativeTo(null);
        tfDescricao.setDocument(new UtilTextField(50,false,true,true,true,""));
        
        getProgramacao();
        progInsUp = new Programacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbProgramacao = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbDescricao = new javax.swing.JLabel();
        btAdicionarCondicao = new javax.swing.JButton();
        tfDescricao = new javax.swing.JTextField();
        lbAtivo = new javax.swing.JLabel();
        cbAtivo = new javax.swing.JComboBox();
        btCancAcao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Programações");
        setModal(true);
        setResizable(false);

        tbProgramacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbProgramacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProgramacaoMouseClicked(evt);
            }
        });
        tbProgramacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbProgramacaoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbProgramacao);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbDescricao.setText("Descrição");

        btAdicionarCondicao.setText("Adicionar");
        btAdicionarCondicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarCondicaoActionPerformed(evt);
            }
        });

        tfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescricaoKeyPressed(evt);
            }
        });

        lbAtivo.setText("Ativo?");

        cbAtivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        cbAtivo.setSelectedIndex(-1);

        btCancAcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raw/150.png"))); // NOI18N
        btCancAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancAcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricao)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdicionarCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancAcao))
                    .addComponent(lbAtivo))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCancAcao)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDescricao)
                            .addComponent(lbAtivo))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdicionarCondicao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarCondicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarCondicaoActionPerformed
        // TODO add your handling code here:
        if (tfDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe uma descrição!");
            tfDescricao.requestFocus();
        } else if (cbAtivo.getSelectedIndex()==-1) {
            JOptionPane.showMessageDialog(null, "Escolha se a programação está ativa!");	
            cbAtivo.requestFocus();
        } else {
            progInsUp.setId(idProg);
            progInsUp.setDescricao(tfDescricao.getText());
            progInsUp.setAtivo(EncodeAtivo(cbAtivo.getSelectedItem().toString()));

            ProgramacaoDAO dao = new ProgramacaoDAO();
            if (idProg==0) {
                try {
                    dao.Inserir(progInsUp);
                    JOptionPane.showMessageDialog(null, "Adicionado com Sucesso!");
                    ClearProgramacao();
                } catch (SQLException e) {
                }
            } else {
                try {   
                    dao.Alterar(progInsUp);
                    JOptionPane.showMessageDialog(null, "Alterado com Sucesso!");
                    btAdicionarCondicao.setText("Adicionar");
                    ClearProgramacao();
                } catch (SQLException e) {
                }
            }
        }
    }//GEN-LAST:event_btAdicionarCondicaoActionPerformed

    private void btCancAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancAcaoActionPerformed
        // TODO add your handling code here:
        ClearProgramacao();
    }//GEN-LAST:event_btCancAcaoActionPerformed

    private void tbProgramacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProgramacaoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DELETE) {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro: \""+ tbProgramacao.getModel().getValueAt(tbProgramacao.getSelectedRow(),1) +"\"?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    ProgramacaoDAO dao = new ProgramacaoDAO();
                    dao.ExcluirProg((Integer) tbProgramacao.getModel().getValueAt(tbProgramacao.getSelectedRow(),0));
                    getProgramacao();
                } catch (SQLException e) {
                }

            }
        }
    }//GEN-LAST:event_tbProgramacaoKeyPressed

    private void tbProgramacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProgramacaoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            btAdicionarCondicao.setText("Alterar");
            idProg = (Integer) tbProgramacao.getModel().getValueAt(tbProgramacao.getSelectedRow(),0);
            tfDescricao.setText(tbProgramacao.getModel().getValueAt(tbProgramacao.getSelectedRow(),1).toString());
            cbAtivo.getModel().setSelectedItem(tbProgramacao.getModel().getValueAt(tbProgramacao.getSelectedRow(),2));
        }
    }//GEN-LAST:event_tbProgramacaoMouseClicked

    private void tfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescricaoKeyPressed
        // TODO add your handling code here:
       
        //int k = evt.getKeyChar();
        if (tfDescricao.getText().length() <= 50 - 1) {
            //deixe passar
        } else {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }//GEN-LAST:event_tfDescricaoKeyPressed

    private void ClearProgramacao(){
        //idAcao=0;
        btAdicionarCondicao.setText("Adicionar");
        cbAtivo.setSelectedIndex(-1);
        tfDescricao.setText("");
        idProg=0;
        getProgramacao();
        tfDescricao.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            // pega aparencia do SO
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
        } 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cadProgramacao().setVisible(true);
       });
    }
    
    public void getProgramacao() {
        try {

            ProgramacaoDAO dao = new ProgramacaoDAO();
            List<Programacao> list = dao.listAll();
            DefaultTableModel dtm = new DefaultTableModel() {
                private static final long serialVersionUID = 1L;
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
            } 
            dtm.addColumn("ID");
            dtm.addColumn("Descrição");
            dtm.addColumn("Ativo");

            list.stream().forEach((programacao) -> {
                dtm.addRow(new Object[] {programacao.getId(), programacao.getDescricao(), DecodeAtivo(programacao.isAtivo())});
            });
            tbProgramacao.setModel(dtm);
        } catch (SQLException e) {
        }
    }
    
    
    
    /**
     * 
     * @param valor boolean
     * @return String
     */
    public String DecodeAtivo(boolean valor) {
        if (valor) {
            return "Sim";
        } else {
            return "Não";
        }
    }

    /**
     * 
     * @param valor String
     * @return boolean
     */
    public boolean EncodeAtivo(String valor) {
        return (valor.equals("Sim"));
    }
	
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarCondicao;
    private javax.swing.JButton btCancAcao;
    private javax.swing.JComboBox cbAtivo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAtivo;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JTable tbProgramacao;
    private javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables
    private int idProg=0;
}
