/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package irrigacao;

import dao.ConfigDAO;
import dao.MapDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import util.Util;
import utilitarios.UtilTextField;

/**
 *
 * @author Marcos Rocha
 */
public final class Config extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
        tfIntervaloRep.setDocument(new UtilTextField(6,false,false,true,false,""));
        tfIntervaloLog.setDocument(new UtilTextField(6,false,false,true,false,""));
        
        tfSensor1Min.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor2Min.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor3Min.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor4Min.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        
        tfSensor1Max.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor2Max.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor3Max.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        tfSensor4Max.setDocument(new UtilTextField(6,false,false,true,false,"-"));
        
        getConfig();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        plGeral = new javax.swing.JPanel();
        tfIntervaloRep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfIntervaloLog = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfSensor1Min = new javax.swing.JTextField();
        tfSensor1Max = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfSensor2Min = new javax.swing.JTextField();
        tfSensor2Max = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfSensor3Min = new javax.swing.JTextField();
        tfSensor3Max = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfSensor4Min = new javax.swing.JTextField();
        tfSensor4Max = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        tfIntervaloRep.setText("10");

        jLabel1.setText("Intervalo de Repetição");

        tfIntervaloLog.setText("1800");

        jLabel2.setText("Intervalo Gravação de Log");

        javax.swing.GroupLayout plGeralLayout = new javax.swing.GroupLayout(plGeral);
        plGeral.setLayout(plGeralLayout);
        plGeralLayout.setHorizontalGroup(
            plGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tfIntervaloLog)
                    .addComponent(tfIntervaloRep))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        plGeralLayout.setVerticalGroup(
            plGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(tfIntervaloRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(tfIntervaloLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geral", plGeral);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor 1"));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 50));

        tfSensor1Min.setText("0");

        tfSensor1Max.setText("100");

        jLabel3.setText("Mínimo:");

        jLabel4.setText("Máximo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor1Min, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor1Max, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSensor1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor1Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor 2"));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 50));

        tfSensor2Min.setText("0");

        tfSensor2Max.setText("100");

        jLabel5.setText("Mínimo:");

        jLabel6.setText("Máximo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor2Min, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor2Max, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor2Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor 3"));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 50));

        tfSensor3Min.setText("0");

        tfSensor3Max.setText("100");

        jLabel7.setText("Mínimo:");

        jLabel8.setText("Máximo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor3Min, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor3Max, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor3Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor3Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensor 4"));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 50));

        tfSensor4Min.setText("0");

        tfSensor4Max.setText("100");

        jLabel9.setText("Mínimo:");

        jLabel10.setText("Máximo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor4Min, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSensor4Max, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor4Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSensor4Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sensores", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // TODO add your handling code here:
        if (!Util.validaInteiro(tfIntervaloRep.getText(),1,604800)){
            jTabbedPane1.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: 1 a 604.800.");
            tfIntervaloRep.requestFocus();
        }else if (!Util.validaInteiro(tfIntervaloLog.getText(),1,604800)){
            jTabbedPane1.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: 1 a 604.800.");
            tfIntervaloLog.requestFocus();
        }else if (!Util.validaInteiro(tfSensor1Min.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor1Min.requestFocus();
        }else if (!Util.validaInteiro(tfSensor1Max.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor1Max.requestFocus();
        }else if (!Util.validaInteiro(tfSensor2Min.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor2Min.requestFocus();
        }else if (!Util.validaInteiro(tfSensor2Max.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor2Max.requestFocus();
        }else if (!Util.validaInteiro(tfSensor3Min.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor3Min.requestFocus();
        }else if (!Util.validaInteiro(tfSensor3Max.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor3Max.requestFocus();
        }else if (!Util.validaInteiro(tfSensor4Min.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor4Min.requestFocus();
        }else if (!Util.validaInteiro(tfSensor4Max.getText(),-32768,32767)){
            jTabbedPane1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null, "Valor fora dos parametros aceitáveis!\nValores aceito: -32.768 a 32.767.");
            tfSensor4Max.requestFocus();
        }else{
        
            setConfig();
            JOptionPane.showMessageDialog(null, "Configurações Gravada com Sucesso!");
            Config.this.dispose();
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        Config.this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // pega aparencia do SO
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
        } 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Config().setVisible(true);
            }
        });
    }
    
    public void getConfig() {
        try {
            ConfigDAO config = new ConfigDAO();
            tfIntervaloRep.setText(config.get("IntervaloRep"));
            tfIntervaloLog.setText(config.get("IntervaloLog"));
        } catch (SQLException e) {
        }
		
        try {
            MapDAO map = new MapDAO();
            tfSensor1Min.setText(map.getMin("$A0").toString());
            tfSensor1Max.setText(map.getMax("$A0").toString());
            tfSensor2Min.setText(map.getMin("$A1").toString());
            tfSensor2Max.setText(map.getMax("$A1").toString());
            tfSensor3Min.setText(map.getMin("$A2").toString());
            tfSensor3Max.setText(map.getMax("$A2").toString());
            tfSensor4Min.setText(map.getMin("$A3").toString());
            tfSensor4Max.setText(map.getMax("$A3").toString());
        } catch (SQLException e) {
        }
    }
    

    public void setConfig(){
        try {
            ConfigDAO config = new ConfigDAO();
            config.set("IntervaloRep", tfIntervaloRep.getText());
            config.set("IntervaloLog", tfIntervaloLog.getText());
        } catch (SQLException e) {
        }
		
        try {
            MapDAO map = new MapDAO();
            map.setMin("$A0", Integer.parseInt(tfSensor1Min.getText()));
            map.setMax("$A0", Integer.parseInt(tfSensor1Max.getText()));
            map.setMin("$A1", Integer.parseInt(tfSensor2Min.getText()));
            map.setMax("$A1", Integer.parseInt(tfSensor2Max.getText()));
            map.setMin("$A2", Integer.parseInt(tfSensor3Min.getText()));
            map.setMax("$A2", Integer.parseInt(tfSensor3Max.getText()));
            map.setMin("$A3", Integer.parseInt(tfSensor4Min.getText()));
            map.setMax("$A3", Integer.parseInt(tfSensor4Max.getText()));
        } catch (SQLException e) {
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel plGeral;
    private javax.swing.JTextField tfIntervaloLog;
    private javax.swing.JTextField tfIntervaloRep;
    private javax.swing.JTextField tfSensor1Max;
    private javax.swing.JTextField tfSensor1Min;
    private javax.swing.JTextField tfSensor2Max;
    private javax.swing.JTextField tfSensor2Min;
    private javax.swing.JTextField tfSensor3Max;
    private javax.swing.JTextField tfSensor3Min;
    private javax.swing.JTextField tfSensor4Max;
    private javax.swing.JTextField tfSensor4Min;
    // End of variables declaration//GEN-END:variables
}
